### ISSUE TITLE
Get the name of the resource

### ISSUE THREAD

**Issue by ericrichtert** [terraform-linters/tflint-ruleset-opa#50]
This is a great tool for applying our own rules to our terraform code!!

But a question about this example (we don't want any aws_security_group_rule resources anymore):
```
package tflint
deny_aws_security_group_rule[issue] {
	rules := terraform.resources("aws_security_group_rule", {"security_group_id": "string"}, {})
	names := rules[_].config.security_group_id
	count(rules) > 0
	issue := tflint.issue(`aws_security_group_rule mag niet meer gebruikt worden, maar komt nog wel voor`, names.range)
}

```
This gives something like:
```
  on terraform\rds.tf line 87:
  87:   security_group_id = "sg-123456"

```
How can I return the name of the resource, instead of a part of the config?

**Comment by bendrucker** [comment]
Try using `__labels`:

https://github.com/search?q=repo%3Aterraform-linters%2Ftflint-ruleset-opa%20__labels&type=code

There's only examples with `dynamic` but in theory this should work for the resource block labels too. If so we should have an example.
